# Generated by Django 3.1.5 on 2021-07-01 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_main', '0002_auto_20210701_0205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
