# Generated by Django 3.1.5 on 2021-07-01 00:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_main', '0004_auto_20210701_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subs',
            field=models.ManyToManyField(related_name='subs', to=settings.AUTH_USER_MODEL),
        ),
    ]
