# Generated by Django 3.1.5 on 2021-07-03 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_main', '0007_auto_20210702_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
