# Generated by Django 3.1.5 on 2021-07-03 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_main', '0009_auto_20210703_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subs',
            field=models.ManyToManyField(related_name='subs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=200)),
                ('video_img', models.ImageField(upload_to='static/video-fg-images/')),
                ('video', models.FileField(upload_to='static/users-videos/')),
                ('caption', models.TextField(max_length=1000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('dislikes', models.ManyToManyField(related_name='VideoDislikes', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(related_name='VideoLikes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_video', to=settings.AUTH_USER_MODEL)),
                ('views', models.ManyToManyField(related_name='videoViews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
