# Generated by Django 3.1.5 on 2021-07-03 13:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_main', '0010_auto_20210703_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subs',
            field=models.ManyToManyField(blank=True, null=True, related_name='subs', to=settings.AUTH_USER_MODEL),
        ),
    ]
